;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Enemy.Health.LowHealth",DevComment="")
+GameplayTagList=(Tag="Enemy.Movement.Crawl",DevComment="")
+GameplayTagList=(Tag="Enemy.Movement.Stand",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Goblin",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Lich",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Skeleton",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Skeleton.Bow",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Skeleton.Sword",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Zombie",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Zombie.Crawl",DevComment="")
+GameplayTagList=(Tag="Enemy.Type.Zombie.Stand",DevComment="")
+GameplayTagList=(Tag="Player.Location.Found",DevComment="")

